version: '3.7'
services:
  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"

  mariadb:
    image: mariadb:10.7.3
    container_name: mariadb
    restart: always
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=True
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      # 데이터베이스 경로
      - ./mariadb:/var/lib/mysql
      # 초기 데이터베이스 설정 
      - ./mariadb/sql/:/docker-entrypoint-initdb.d/
      # config 설정
      - ./mariadb/config/:/etc/mysql/conf.d
    ports:
      - 3307:3306

  docker-fastapi:
    container_name: docker-fastapi
    build: .
    restart: always
    ports:
      - 8000:8000
    volumes:
      # 개발 환경에서 소스코드를 수정했을 때 일일이 빌드안해도 적용할 수 있도록
      # 로컬의 소스코드를 볼륨으로 탑재
      - ./app:/app
    environment:
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_PORT=${MARIADB_PORT}
